### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by chemicstry** [tpoisonooo/rust-ncnn#3]
Hi, thanks for a great crate!

I have a few questions:
- What is the reason for using `ncnn` fork instead of original repository? They seem the same except for an old version.
- Would it make sense to make static build the default one? It seems like that is the usual use-case. Setting env variable for all projects seems redudant.

**Comment by tpoisonooo** [comment]
1.  ncnn may updates,  I am afraid of that `rust-ncnn` not compatible with ncnn new version
2. OK, let's make a  static build

**Comment by chemicstry** [comment]
Sorry for not updating, I have since learned that rust defaults to static linking on windows and dynamic on linux. This is what I currently have as defaults in my fork. I couldn't get dynamic build to work on windows or static on linux. Maybe it's something with my configuration.

As for nccn version, you can just pin it to a released version with git tag https://github.com/lit-robotics/rust-ncnn/blob/master/ncnn-bind/build.rs#L37

**Comment by tpoisonooo** [comment]
BTW,  ncnn never use uppercase ...  our lovely ncnn owner said `NCNN` is not cute.

**Comment by chemicstry** [comment]
Thanks for merging our repo, this issue is now irrelevant.
